
### connect-with-group-leak
PUT http://localhost:58080/api/tcp/client/connect/event-loop-group/leak/127.0.0.1/12346
Accept: application/json

### connect-with-group-release
PUT http://localhost:58080/api/tcp/client/connect/event-loop-group/release/127.0.0.1/12346
Accept: application/json

### disconnect-with-group
DELETE http://localhost:58080/api/tcp/client/connect/event-loop-group/disconnect