
### connect-with-eventloop-leak
PUT http://localhost:58080/api/tcp/client/event-loop/connect/leak/127.0.0.1/12346
Accept: application/json

### connect-with-eventloop-release
PUT http://localhost:58080/api/tcp/client/event-loop/connect/release/127.0.0.1/12346
Accept: application/json

### disconnect-with-eventloop
DELETE http://localhost:58080/api/tcp/client/event-loop/disconnect